#!/system/bin/sh
# =============================================================================
# netshare_ap.sh - create a second WiFi network as root, no hotspot toggle
#
# USAGE (as root):
#   sh /data/local/tmp/netshare_ap.sh start <ssid> <passphrase> [channel]
#   sh /data/local/tmp/netshare_ap.sh stop
#   sh /data/local/tmp/netshare_ap.sh status
#
# WHAT THIS IS
#   The "NetShare" idea: the phone stays associated to its own WiFi (that is the
#   internet side) and at the same time runs an access point for customers, so
#   nobody has to switch the Android hotspot on. This is the rooted version -
#   instead of asking the framework, it asks the WiFi driver directly:
#
#     iw dev wlan0 interface add rnsap0 type __ap     (a second virtual interface)
#     <vendor hostapd> -B /data/local/tmp/netshare_hostapd.conf
#
#   setup_network.sh then does NAT/DHCP/portal on that interface like any other
#   LAN, and adds the `ip rule` entries Android's routing would otherwise need.
#
# WHEN IT CANNOT WORK
#   Only if the driver supports STA+AP concurrency. When it does not, `iw` says
#   so explicitly and that message is written to the log - which is the point:
#   a definite answer instead of an AP that silently never appears.
#
# EVERY line this script prints is captured by the app's debugger.
# =============================================================================

STATE_DIR="${HOTSPOT_STATE_DIR:-/data/local/tmp}"
CONF_FILE="${HOTSPOT_NETSHARE_CONF:-$STATE_DIR/netshare_hostapd.conf}"
RUNTIME_FILE="${HOTSPOT_NETSHARE_RUNTIME:-$STATE_DIR/netshare.runtime}"
PIDFILE="$STATE_DIR/netshare_hostapd.pid"
HOSTAPD_LOG="$STATE_DIR/netshare_hostapd.log"
IFACE_NAME="${HOTSPOT_NETSHARE_IFACE:-rnsap0}"
AP_IP="${HOTSPOT_NETSHARE_IP:-192.168.50.1}"
AP_PREFIX="${HOTSPOT_NETSHARE_PREFIX:-24}"
MAX_STA="${HOTSPOT_NETSHARE_MAX_STA:-32}"

log() { echo "[netshare_ap] $*"; }
err() { echo "[netshare_ap] ERROR: $*" >&2; }
die() { echo "[netshare_ap] ERROR: $*" >&2; exit 1; }

# ------------------------------------------------------------------ discovery

# The interface the phone is using for internet. That is the radio we ask for a
# second interface on (a different radio would need a different channel).
find_sta_interface() {
    STA=$(ip route show default 2>/dev/null | sed -n 's/.* dev \([^ ]*\).*/\1/p' | head -n 1)
    if [ -z "$STA" ]; then
        for candidate in wlan0 wlan1 eth0 ccmni0; do
            if [ -d "/sys/class/net/$candidate" ]; then STA="$candidate"; break; fi
        done
    fi
    echo "$STA"
}

# The channel the STA is on. A concurrent AP must share it on single-radio chips.
find_channel() {
    STA="$1"
    CH=$(iw dev "$STA" info 2>/dev/null | sed -n 's/.*channel \([0-9]*\).*/\1/p' | head -n 1)
    [ -n "$CH" ] && echo "$CH" && return 0
    # Some vendors only expose it through wpa_cli.
    CH=$(wpa_cli -i "$STA" status 2>/dev/null | sed -n 's/^freq=//p' | head -n 1)
    if [ -n "$CH" ]; then freq_to_channel "$CH"; return 0; fi
    echo ""
}

freq_to_channel() {
    F="$1"
    case "$F" in
        24*) echo $(( (F - 2407) / 5 )) ;;
        5*)  echo $(( (F - 5000) / 5 )) ;;
        *)   echo "" ;;
    esac
}

find_hostapd() {
    for candidate in /vendor/bin/hw/hostapd /system/bin/hostapd /vendor/bin/hostapd \
                     /system/xbin/hostapd /data/local/tmp/hostapd; do
        [ -x "$candidate" ] && echo "$candidate" && return 0
    done
    # Last resort: whatever is on PATH.
    command -v hostapd 2>/dev/null
}

find_iw() {
    for candidate in /system/bin/iw /vendor/bin/iw /data/local/tmp/iw; do
        [ -x "$candidate" ] && echo "$candidate" && return 0
    done
    command -v iw 2>/dev/null
}

hostapd_running() {
    [ -f "$PIDFILE" ] || return 1
    P=$(cat "$PIDFILE" 2>/dev/null)
    [ -n "$P" ] && kill -0 "$P" 2>/dev/null && return 0
    return 1
}

iface_exists() {
    [ -d "/sys/class/net/$1" ]
}

write_runtime() {
    IFACE="$1"; SSID="$2"; PASS="$3"; CHANNEL="$4"; MODE="$5"
    cat > "$RUNTIME_FILE" <<EOF
IFACE=$IFACE
SSID=$SSID
PASS=$PASS
CHANNEL=$CHANNEL
MODE=$MODE
CREATED=$CREATED
AP_IP=$AP_IP/$AP_PREFIX
HOSTAPD=$HOSTAPD_BIN
EOF
    # stdout is what the app parses; keep these lines stable.
    echo "IFACE=$IFACE"
    echo "SSID=$SSID"
    echo "PASS=$PASS"
    echo "CHANNEL=$CHANNEL"
    echo "MODE=$MODE"
    echo "CREATED=$CREATED"
}

# ------------------------------------------------------------------ hostapd conf

write_conf() {
    IFACE="$1"; SSID="$2"; PASS="$3"; CHANNEL="$4"
    HW_MODE=g
    if [ -n "$CHANNEL" ] && [ "$CHANNEL" -gt 14 ] 2>/dev/null; then HW_MODE=a; fi
    cat > "$CONF_FILE" <<EOF
# Generated by netshare_ap.sh - do not edit while the gateway is running.
interface=$IFACE
driver=nl80211
ctrl_interface=$STATE_DIR/netshare_hostapd.sock
ssid=$SSID
hw_mode=$HW_MODE
EOF
    if [ -n "$CHANNEL" ]; then
        echo "channel=$CHANNEL" >> "$CONF_FILE"
    else
        log "no channel could be determined - letting hostapd pick"
    fi
    cat >> "$CONF_FILE" <<EOF
beacon_int=100
dtim_period=2
max_num_sta=$MAX_STA
supported_rates=60 90 120 180 240 360 480 540
wpa=2
wpa_passphrase=$PASS
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_pairwise=TKIP CCMP
ignore_broadcast_ssid=0
wmm_enabled=1
EOF
    log "wrote $CONF_FILE (interface=$IFACE ssid=$SSID hw_mode=$HW_MODE channel=${CHANNEL:-auto})"
}

# ------------------------------------------------------------------ commands

# Bring the interface up with an address, so DHCP has something to serve from
# even if hostapd's own driver init does not.
address_interface() {
    IFACE="$1"
    ip link set "$IFACE" up 2>/dev/null || log "could not set $IFACE up"
    CURRENT=$(ip -o -4 addr show dev "$IFACE" 2>/dev/null | awk '{print $4}' | head -n 1)
    if [ -z "$CURRENT" ]; then
        ip addr add "$AP_IP/$AP_PREFIX" dev "$IFACE" 2>/dev/null \
            && log "assigned $AP_IP/$AP_PREFIX to $IFACE" \
            || log "could not assign $AP_IP/$AP_PREFIX to $IFACE (setup_network.sh will retry)"
    else
        # Adopt whatever is already there - same rule the main script follows.
        AP_IP="${CURRENT%/*}"
        AP_PREFIX="${CURRENT#*/}"
        log "adopting the existing address $CURRENT on $IFACE"
    fi
    echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null
}

start() {
    SSID="$1"
    PASS="$2"
    WANT_CHANNEL="$3"

    [ -n "$SSID" ] || die "usage: start <ssid> <passphrase> [channel]"
    if [ "${#PASS}" -lt 8 ]; then
        die "passphrase must be at least 8 characters (got ${#PASS})"
    fi

    if hostapd_running; then
        log "hostapd from a previous run is still alive (pid $(cat "$PIDFILE"))"
        . "$RUNTIME_FILE" 2>/dev/null
        if [ -n "$IFACE" ] && iface_exists "$IFACE"; then
            write_runtime "$IFACE" "$SSID" "$PASS" "$CHANNEL" "already-running"
            return 0
        fi
        stop
    fi

    IW=$(find_iw)
    HOSTAPD_BIN=$(find_hostapd)
    STA=$(find_sta_interface)
    log "discovered: sta=${STA:-none} iw=${IW:-none} hostapd=${HOSTAPD_BIN:-none}"

    [ -n "$STA" ] || die "no internet-side interface found - connect the phone to WiFi first"
    [ -n "$HOSTAPD_BIN" ] || die "no hostapd binary on this device (looked in /vendor/bin/hw, /system/bin, /vendor/bin)"

    CHANNEL="$WANT_CHANNEL"
    if [ -z "$CHANNEL" ]; then
        CHANNEL=$(find_channel "$STA")
        log "channel on $STA: ${CHANNEL:-unknown}"
    fi

    # 1. An interface we can put an AP on. Prefer one that already exists
    #    (p2p0 / ap0 / wlan1) over creating one - creating needs driver support.
    NEW_IF=""
    CREATED=0
    for candidate in "$IFACE_NAME" p2p0 ap0 wlan1 softap0 swlan0; do
        if iface_exists "$candidate" ] && [ "$candidate" != "$STA" ]; then
            STATE=$(ip -o link show "$candidate" 2>/dev/null)
            case "$STATE" in
                *UP*) NEW_IF="$candidate"; CREATED=0; log "reusing the existing AP-capable interface $candidate";;
            esac
            [ -n "$NEW_IF" ] && break
        fi
    done

    if [ -z "$NEW_IF" ]; then
        if [ -z "$IW" ]; then
            die "no usable AP interface ($IFACE_NAME/p2p0/ap0/wlan1) and no 'iw' binary to create one"
        fi
        log "asking the driver for a second interface: iw dev $STA interface add $IFACE_NAME type __ap"
        if $IW dev "$STA" interface add "$IFACE_NAME" type __ap 2>>"$HOSTAPD_LOG"; then
            NEW_IF="$IFACE_NAME"; CREATED=1
            log "driver accepted type __ap"
        else
            log "type __ap refused; trying type managed"
            if $IW dev "$STA" interface add "$IFACE_NAME" type managed 2>>"$HOSTAPD_LOG"; then
                NEW_IF="$IFACE_NAME"; CREATED=1
                log "driver accepted type managed (hostapd will try to switch it to AP mode)"
            else
                die "the WiFi driver refused to create a second interface on $STA - this chip " \
                    "cannot run an AP and a WiFi connection at the same time. Use the Android " \
                    "hotspot toggle instead (see the debugger log for the driver's answer)."
            fi
        fi
    fi

    address_interface "$NEW_IF"
    write_conf "$NEW_IF" "$SSID" "$PASS" "$CHANNEL"

    : > "$HOSTAPD_LOG"
    log "starting $HOSTAPD_BIN -B $CONF_FILE"
    "$HOSTAPD_BIN" -B -P "$PIDFILE" "$CONF_FILE" >>"$HOSTAPD_LOG" 2>&1
    sleep 3

    if ! hostapd_running; then
        TAIL=$(tail -n 8 "$HOSTAPD_LOG" 2>/dev/null)
        die "hostapd exited immediately. Last lines: ${TAIL:-none}"
    fi

    # Confirm it really is beaconing, not just alive.
    if [ -n "$IW" ]; then
        log "iw dev $NEW_IF info: $($IW dev "$NEW_IF" info 2>/dev/null | tr '\n' ';')"
    fi
    log "AP up: $SSID on $NEW_IF (pid $(cat "$PIDFILE"))"
    write_runtime "$NEW_IF" "$SSID" "$PASS" "$CHANNEL" "root-hostapd"
}

stop() {
    IFACE=""
    CREATED=""
    # shellcheck disable=SC1090
    [ -f "$RUNTIME_FILE" ] && . "$RUNTIME_FILE"
    if hostapd_running; then
        P=$(cat "$PIDFILE")
        log "stopping hostapd (pid $P)"
        kill "$P" 2>/dev/null
        sleep 1
        kill -9 "$P" 2>/dev/null
    fi
    rm -f "$PIDFILE"
    TARGET="${IFACE:-$IFACE_NAME}"
    if [ "$CREATED" = "1" ]; then
        IW=$(find_iw)
        if [ -n "$IW" ]; then
            log "removing the interface this script created ($TARGET)"
            $IW dev "$TARGET" del 2>/dev/null || log "the driver refused to remove $TARGET"
        else
            log "no iw binary - cannot remove $TARGET"
        fi
    else
        log "leaving $TARGET in place (this script did not create it)"
    fi
    rm -f "$RUNTIME_FILE"
    log "stopped"
}

status() {
    echo "-- netshare_ap runtime --"
    [ -f "$RUNTIME_FILE" ] && cat "$RUNTIME_FILE" || echo "(not started by this script)"
    if hostapd_running; then
        echo "hostapd            : running (pid $(cat "$PIDFILE"))"
    else
        echo "hostapd            : stopped"
    fi
    echo "-- interfaces --"
    ip -o link show 2>/dev/null
    echo "-- addresses --"
    ip -o -4 addr show 2>/dev/null
    echo "-- hostapd log (tail) --"
    tail -n 20 "$HOSTAPD_LOG" 2>/dev/null
    echo "-- discovery --"
    echo "iw                 : $(find_iw)"
    echo "hostapd            : $(find_hostapd)"
    echo "sta interface      : $(find_sta_interface)"
}

case "${1:-}" in
    start)  start "${2:-}" "${3:-}" "${4:-}" ;;
    stop)   stop ;;
    status) status ;;
    *) echo "usage: $0 {start <ssid> <passphrase> [channel]|stop|status}" ;;
esac
